[profile.default]
src = "lib"
out = "out"
libs = ["lib"]
auto_detect_remappings = false
chain_id = 1
auto_detect_solc = false
solc_version = "0.8.20"
evm_version = "shanghai"
via_ir = false
cbor_metadata = true
use_literal_content = false
bytecode_hash = "ipfs"
optimizer = true
optimizer_runs = 200
libraries = ["lib/aave-v3-origin/src/contracts/protocol/libraries/logic/BorrowLogic.sol:BorrowLogic:0x4c52FE2162200bf26c314d7bbd8611699139d553", "lib/aave-v3-origin/src/contracts/protocol/libraries/logic/BridgeLogic.sol:BridgeLogic:0x97dCbFaE5372A63128F141E8C0BC2c871Ca5F604", "lib/aave-v3-origin/src/contracts/protocol/libraries/logic/ConfiguratorLogic.sol:ConfiguratorLogic:0x3a593A622754ed9572599D33Aad6D799B0899Fae", "lib/aave-v3-origin/src/contracts/protocol/libraries/logic/EModeLogic.sol:EModeLogic:0x88F864670De467aA73CD45325F9652C578C8AB85", "lib/aave-v3-origin/src/contracts/protocol/libraries/logic/FlashLoanLogic.sol:FlashLoanLogic:0xb32381feFFF45eE9F47fD2f2cF83C832637d6EF0", "lib/aave-v3-origin/src/contracts/protocol/libraries/logic/LiquidationLogic.sol:LiquidationLogic:0x80d16970B31243Fe67DaB028115f3E4c3E3510Ad", "lib/aave-v3-origin/src/contracts/protocol/libraries/logic/PoolLogic.sol:PoolLogic:0xA58FB47bE9074828215A173564C0CD10f6F249bf", "lib/aave-v3-origin/src/contracts/protocol/libraries/logic/SupplyLogic.sol:SupplyLogic:0x2b22E425C1322fbA0DbF17bb1dA25d71811EE7ba"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
